### ISSUE TITLE
Error! code - 33 does not exist!

### ISSUE THREAD

**Issue by tayler0101** [stuicey/SSHy#20]
when i try to connect to another device on the same network it give this error, but when i try 127.0.0.1 it work just fine.
RSA signature verification failed, disconnecting. transport.js:363:13
Error! code - 33 does not exist!
wsproxy:
[Info]: Requested connection from '::ffff:127.0.0.1' to '192.168.52.159:22' [ACCEPTED].
[Status]: Connection accepted from '192.168.52.159:22'.
[Info]: Connection closed from '192.168.52.159:22'.
[Info]: Connection closed from '::ffff:127.0.0.1'.
[Info]: Connection closed from '192.168.52.159:22'.
[Info]: Connection closed from '::ffff:127.0.0.1'.
any idea ?

**Comment by stuicey** [comment]
Looks like the RSA signature provided by the server is being rejected by the client and as such is immediately disconnecting:
```
if(!rsa.verify(SSHyClient.kex.H, new SSHyClient.Message(sig))){
	transport.disconnect();
	throw 'RSA signature verification failed, disconnecting.';
}
```
When you first connect it will ask you to confirm the signature and then store it in the browser's local storage if you accept it. You could try clearing the browser's local storage for the client's website:

`developer tools > application > local storage > [ website ] > right-click > clear` (chrome)

Would be interesting to find out why this has occurred though, I'd guess the SSH server at [address:port] changed?

**Comment by tayler0101** [comment]
i don't know why it doesn't work, i use Firefox in private mode there is no cache.
soi i disable rsa.verify then i have the error 1005
WebSocket connection failed: Error in connection establishment: code 1005

**Comment by stuicey** [comment]
That's pretty odd, did you fully close the private session? Firefox will treat localStorage as sessionStorage in private sessions, so it wont be cleared until you restart the browser.

Have you tried using the wrapper version? That has key verification disabled by default, alternatively the proper way to disable it is to edit [js/settings.js](https://github.com/stuicey/SSHy/blob/master/js/settings.js#L30).

**Comment by tayler0101** [comment]
ya i already done all everything delete the LocalStorage manually close the Browser and re open it even i tried to debug the code to see what goes wrong and what is the differences between t locally and remotely,
in remote mode it receive 4 messages and close the connection with transport.disconnect and if i disable the rsa then it goes to ws.onclose with error 1005

**Comment by stuicey** [comment]
Hmm, could you try adding additional debugging to `js/parceler.js` so we can see what messages are getting passed back and forth?

`console.log(data.toString());` to https://github.com/stuicey/SSHy/blob/master/js/parceler.js#L29
&&
`console.log(r.toString());` to https://github.com/stuicey/SSHy/blob/master/js/parceler.js#L66

I'm wondering if the server is closing the connection after the client [sends the new keys](https://github.com/stuicey/SSHy/blob/master/js/transport.js#L385) due to a mismatch. I doubt its an issue with the key exchange code but could be that some data isn't being passed in correctly.

**Comment by tayler0101** [comment]
so i think i found the problem but i don't know why it happen, after key exchange the client send "user authentication" to server after, but it encrypt the packet, the encrypted packet either not correct or the server read it wrong :
> Nov 30 17:47:23 test-os sshd[4303]: debug2: set_newkeys: mode 0 [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: debug1: rekey after 4294967296 blocks [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: debug1: KEX done [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: Bad packet length 69315617. [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: debug3: send packet: type 1 [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: ssh_dispatch_run_fatal: Connection from 192.168.0.131 port 36092: message authentication code incorrect [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: debug1: do_cleanup [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: debug3: PAM: sshpam_thread_cleanup entering [preauth]
> Nov 30 17:47:23 test-os sshd[4303]: debug1: monitor_read_log: child log fd closed
> Nov 30 17:47:23 test-os sshd[4303]: debug3: mm_request_receive entering
> Nov 30 17:47:23 test-os sshd[4303]: debug1: do_cleanup
> Nov 30 17:47:23 test-os sshd[4303]: debug3: PAM: sshpam_thread_cleanup entering
> Nov 30 17:47:23 test-os sshd[4303]: debug1: Killing privsep child 4306
> Nov 30 17:47:23 test-os sshd[4303]: debug1: audit_event: unhandled event 12
> Nov 30 17:47:23 test-os systemd[1]: ssh.service: Main process exited, code=exited, status=255/n/a
> Nov 30 17:47:23 test-os systemd[1]: ssh.service: Unit entered failed state.
> Nov 30 17:47:23 test-os systemd[1]: ssh.service: Failed with result 'exit-code'.
it is really wired coz it work just fine with another ssh server

**Comment by stuicey** [comment]
Yeah that is strange, from the output it looks like the server is rejecting the connection as the HMAC is incorrect. The HMAC key generation is fairly complicated but it all stems from the value calculated here:
```js
/*
   Now we need to generate H = hash(V_C || V_S || I_C || I_S || K_S || e || f || K)
   where	V_ = identification string,	K_ = public host key,	I_ = SSH_MSG_KEXINIT message
*/
var m = new SSHyClient.Message();
m.add_string(this.transport.local_version);
m.add_string(this.transport.remote_version);
m.add_string(this.transport.local_kex_message);
m.add_string(this.transport.remote_kex_message);
m.add_string(host_key);
// Only add these if we're using DH GEX
if(this.group === undefined){
	m.add_int(this.minBits);
	m.add_int(this.preferredBits);
	m.add_int(this.maxBits);
	m.add_mpint(this.p);
	m.add_mpint(this.g);
}
m.add_mpint(this.e);
m.add_mpint(this.f);
m.add_mpint(K);
```
Since the key exchange works with other systems I'm inclined to ignore variables that are generated during the key exchange algorithm itself and by SSHy. This should just leave `remote_version` & `remote_kex_message`. I think its more likely that the issue is with the `remote_version` as it can be an arbitrary UTF-8 string that the client/server developers define. I imagine the device that isn't working is some kind of network device with its own customised version of SSH?

Good news is this should be fairly quick to validate. You'll need to use a network monitoring tool like wireshark to see whats being transmitted over the network and compare with what SSHy is receiving. Host wsproxy on the same machine so you can see the un-encoded SSH packets and filter by them (or use another SSH client). One of the first two packets should contain the servers identification string, it will start like `SSH-2.0*` or `53 53 48 2d 32 2e 30 0d 0a **` in hex. You can then compare this to what SSHy has used to generate the HMAC by using the following in the JS console:

```js
console.log(transport.remote_version)
ascii2hex(transport.remote_version)
```

**Comment by tayler0101** [comment]
any idea why?
`this.preferred_mac undefined`
and it work!!!!

**Comment by stuicey** [comment]
Definitely strange... 🤔 

Would need to see the key exchange (KEX) init message to confirm but maybe your SSH server requested "none" as the MAC algorithm? The client should have dropped the connection there though if there was no matching algorithm and the server shouldn't be expecting "none" as the client doesn't offer that. Without a MAC algorithm there will be no verification of the packet's origin on the SSH client/server, hence why I didn't include it.

I'd be interested in seeing the `remote_kex_message` to see why the connection wasn't dropped.

**Comment by tayler0101** [comment]
at the end the wrong was :
`self.remote_version = m.slice(0, m.length - 2);` -2 is wrong in my case -1 is write
its look like the code throw last two bytes away assuming that they are "\r\n" or something similar, while its just "\n"
i used to solve the problem:
`m.match(/.+/)[0].replace(/\s$/,"");`

**Comment by stuicey** [comment]
Ok, that makes sense. **Very** old, undocumented versions of SSH don't send a carriage return character as part of their identification string. The SSH specification states the following:

> The identification MUST be terminated by a single Carriage Return (CR) and a single Line Feed (LF) character (ASCII 13 and 10, respectively).

Going to have to think about whether I want to fix this or not to be compatible with older systems. I'd rather see people update the servers but I also understand that isn't always possible..

**Comment by tayler0101** [comment]
i think you have write, but in my case i am using debian and the ssh version is last version for my system ,thank for your help.

**Comment by tayler0101** [comment]
hi man, did you worked on public key authentication?

**Comment by stuicey** [comment]
Hey, haven't had chance to  look into it yet - half the battle is finding the RFC documentation specifying how it should be implemented. The ideal scenario would be if the client only needs to request public key authentication and then send the key as is since that could be implemented in a few minutes.

**Comment by tayler0101** [comment]
i don't if you have time to help i already asked too much, but if you have i can tell what i did do until now.
