### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by jtkaufman737** [stuicey/SSHy#22]
I'm integrating your work on SSHy into a project at work (and sorry for the vagueness of this question but it is bound by confidentiality). 

I'm curious off the top of your head if you have any ideas where a certain behavior is coming from - although I realize without more detail this is kind of a shot in the dark.

I'm having something occur on Firefox where about every 1/20 times I launch SSHy, the text isn't visible until I either resize or reload the window. I haven't found much on StackOverflow about this library so I figured I would run it by you in case you had any ideas of things I could look at that might be causing similar behavior.

(Images before and directly after resizing horizontally) 

<img width="1068" alt="screen shot 2019-02-07 at 4 10 52 pm" src="https://user-images.githubusercontent.com/18295492/52443183-0fae2000-2af3-11e9-927d-4ea93ccdc00e.png">
<img width="944" alt="screen shot 2019-02-07 at 4 11 15 pm" src="https://user-images.githubusercontent.com/18295492/52443184-0fae2000-2af3-11e9-80b8-36cf47da7eca.png">

If nothing comes to mind, I totally understand & thanks anyway :)

**Comment by stuicey** [comment]
Hey,

Hopefully I can help out - I think it might have something to do with `term.fit()` [xterm.min.js](https://github.com/stuicey/SSHy/blob/82941c8ae15359fd387109dcee3a218808df0bb0/js/src/xterm.min.js#L6599) its an addon for `xterm.js` which calculates rows/columns based on the parent container. It is called when the terminal is initialised and on window resize and relays the new rows/columns will be relayed to the SSH server.

You could test the current rows/columns with `console.log("rows:"+term.rows+" cols:"+term.cols)` and see if your screen is blank because they're set to 0. If they are set to 0 it might be something to do with your parent element? term.fit() won't work if the parent element is hidden so maybe a race condition in play?

Might also just be worth updating `xterm.js` to the most recent release, I can't see any of the features SSHy relies on having changed massively so should be fairly painless to try.

**Comment by jtkaufman737** [comment]
Hi, thanks for getting back to me. It does look like the terminal is getting made correctly, I'm not sure if anything else comes to mind? 
<img width="790" alt="screen shot 2019-02-19 at 1 34 13 pm" src="https://user-images.githubusercontent.com/18295492/53038606-289bc700-344b-11e9-959e-78e9f2d4d01d.png">

**Comment by jtkaufman737** [comment]
Actually, I think I came up with a solution! Thank you for taking a look though
