### ISSUE TITLE
Installing SSHy and WSProxy

### ISSUE THREAD

**Issue by OoLunar** [stuicey/SSHy#24]
Trying to install SSHy and WSProxy. Steps I did were:
```bash
git clone https://github.com/stuicey/SSHy.git
nvm use 9.6.1
#Now using node v9.6.1 (npm v6.9.0)
npm i -g wsproxy
#Installation was fine. No errors or anything.
```
I attempt to go to https://forsaken-borders.net/dev/ssh, and then those errors show up...
![Screenshot 2019-05-03 at 10 45 54](https://user-images.githubusercontent.com/46751150/57149181-c3d8e300-6d90-11e9-9931-e26b0826a434.png)

Any clues?

**Comment by stuicey** [comment]
It looks like you might have installed the version of wsproxy published on npm instead of my fork, the websocket protocol spec changed a while ago and I'm not sure if the official version has that patch. Try execute the following commands from the folder you've cloned the SSHy repo to. (note the `/` on `wsproxy/`) 

```
git submodule update --init --recursive
npm i -g  wsproxy/
wsproxy
```

**Comment by OoLunar** [comment]
![image](https://user-images.githubusercontent.com/46751150/57174160-819aba80-6dff-11e9-89fa-fae158e81a95.png)

![image](https://user-images.githubusercontent.com/46751150/57174161-8cede600-6dff-11e9-8aba-2f015c598bcb.png)

Progress... I haven't touched anything else. Any other steps I'm missing?

**Comment by stuicey** [comment]
Its trying to open a secure websocket connection (`wss://`) as you have opened the page with `https`. Most web browsers don't allow unsecure websocket connections over https. You'll need to either provide a cert for wsproxy to use, refer to: [wsproxy readme](https://github.com/stuicey/wsproxy); or open the page with http.

**Comment by OoLunar** [comment]
So then, I would just replace ``wss://`` with ``https://``?

**Comment by stuicey** [comment]
You'll either need to provide a certificate & private key to `wsproxy` so it can host a secure websocket server `wss://` e.g.
`wsproxy -s -c [certificate_chain_file] -k [private_key_file]` 

or, you'll need to access the SSHy webpage via `http://` so that it will use unsecure websockets `ws://`

Since the SSH connection is encrypted in browser you're not hiding much by using `https://`, would just be the pre-authentication information and SSH server ip.

**Comment by kidygetnada** [comment]
I am new to this so I am sorry for a stupid question, but is it possible to install wsproxy manually, without npm or avoid it altogether? I want to use SSH only to connect to my machine (where sshy is installed) from elsewhere...
